version: '3.8'
services:

  interview-task-service1:
    container_name: interview-service
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      CDQ_DATABASE_NAME: tasks
      CDQ_DATABASE_HOST: postgresql
      CDQ_DATABASE_PORT: 5432
      CDQ_DATABASE_USERNAME: interview_user
      CDQ_DATABASE_PASSWORD: interview_pass

  db:
    container_name: interview-postgresql
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: interview_user
      POSTGRES_PASSWORD: interview_pass
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - interview-adamus-postgres_data:/data/db

#           OPTIONAL PG ADMIN
#  pgadmin:
#    container_name: interview-pgadmin4
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: password
#    ports:
#      - "8100:80"
#    volumes:
#      - interview-adamus-pgadmin_data:/data/pgadmin

volumes:
  interview-adamus-postgres_data:
  interview-adamus-pgadmin_data:
