version: '3.8'
services:
#         InterviewService with api and worker
  interview-service-api-worker:
    container_name: interview-service-api-worker
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile
    ports:
      - "8080:8080"
      - "5701:5701"
    environment:
      #Delay in message processing to simulate long running task
      CDQ_PROCESSING_DELAY: 750ms
      #Hazelcast config
      CDQ_HAZELCAST_OWN: interview-service-api-worker
      CDQ_HAZELCAST_OTHERS: interview-service-api,interview-service-worker
      #Database
      CDQ_DATABASE_NAME: tasks
      CDQ_DATABASE_HOST: interview-postgresql
      CDQ_DATABASE_PORT: 5432
      CDQ_DATABASE_USERNAME: interview_user
      CDQ_DATABASE_PASSWORD: interview_pass

#         InterviewService
  interview-service-api:
    container_name: interview-service-api
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile
    ports:
      - "8081:8080"
      - "5702:5701"
    environment:
      #Delay in message processing to simulate long running task
      CDQ_PROCESSING_DELAY: 750ms
      #Hazelcast config
      CDQ_HAZELCAST_OWN: interview-service-api
      CDQ_HAZELCAST_OTHERS: interview-service-api-worker,interview-service-worker
      #Database
      CDQ_DATABASE_NAME: tasks
      CDQ_DATABASE_HOST: interview-postgresql
      CDQ_DATABASE_PORT: 5432
      CDQ_DATABASE_USERNAME: interview_user
      CDQ_DATABASE_PASSWORD: interview_pass

#         InterviewService
  interview-service-worker:
    container_name: interview-service-worker
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile
    ports:
      - "8082:8080"
      - "5703:5701"
    environment:
      #Delay in message processing to simulate long running task
      CDQ_PROCESSING_DELAY: 750ms
      #Hazelcast config
      CDQ_HAZELCAST_OWN: interview-service-worker
      CDQ_HAZELCAST_OTHERS: interview-service-api-worker,interview-service-api
      #Database
      CDQ_DATABASE_NAME: tasks
      CDQ_DATABASE_HOST: interview-postgresql
      CDQ_DATABASE_PORT: 5432
      CDQ_DATABASE_USERNAME: interview_user
      CDQ_DATABASE_PASSWORD: interview_pass

#           PostgreSQL
  db:
    container_name: interview-postgresql
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: interview_user
      POSTGRES_PASSWORD: interview_pass
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - interview-adamus-postgres_data:/data/db

#           Rabbit MQ
  rabbitmq:
    image: rabbitmq:3.12.0-rc.1-management
    container_name: interview-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - interview-adamus-rabbit_data:/var/lib/rabbitmq/
      - interview-adamus-rabbit_log:/var/log/rabbitmq

#           OPTIONAL PG ADMIN
#  pgadmin:
#    container_name: interview-pgadmin4
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: password
#    ports:
#      - "8100:80"
#    volumes:
#      - interview-adamus-pgadmin_data:/data/pgadmin

volumes:
  interview-adamus-postgres_data:
  interview-adamus-pgadmin_data:
  interview-adamus-rabbit_data:
  interview-adamus-rabbit_log:
